[package]
name = "records_lib"
version = "0.2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
async-graphql = { version = "5.0.5", features = ["dataloader", "apollo_tracing"] }
sqlx = { version = "0.6.2", features = [ "runtime-tokio-native-tls", "mysql", "macros", "chrono" ] }
chrono = "0.4"
deadpool = { version = "0.9.5", features = ["managed", "rt_tokio_1"] }
deadpool-redis = { version = "0.11.1", features = ["rt_tokio_1"] }
serde = "1.0.126"
thiserror = "1.0"
actix-web = "4.3.0"
reqwest = "0.11.14"
